server:
  port: 9090

spring:
  application:
    name: dubbo-consumer

dubbo:
  registry:
    address: zookeeper://a:2181
  consumer:
    # 全局性设置负载均衡方式
    loadbalance: leastactive

project:
  service:
    version: 1.0.0